### PR TITLE
Upgrade NGINX from v1.19.8 to v1.19.10

### PR DESCRIPTION
**Pull request by mathieu-aubin**

### CODE REVIEW

**Comment by ericpruitt** [comment]
Thanks for submitting this diff.

**Comment by mathieu-aubin** [comment]
i have made the pull a bit too fast maybe, not thinking about the patch and not having tested. This is pretty 'green' on my part. Hopefuly things still work as intended...

**Comment by ericpruitt** [comment]
I tested the patch locally before I merged it.

**Comment by ericpruitt** [comment]
I know rewriting history is generally frowned upon, but merging this commit from the GitHub web UI didn't work as intended, and I don't like the way the commits were done. I'm going to reset the repo and apply the change from the command line and force-push the updated repo, so you won't be able do a standard pull since the repos will have diverged.

**Comment by ericpruitt** [comment]
Done. HEAD is now 91e3da26af98fd9914ff51c272053d90ea865fd0 which includes a Make target for testing the NGINX binary.

**Pull request merged**
